service: api-tts
frameworkVersion: '4.1.11'

provider:
  name: aws
  runtime: python3.9

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  text_to_speech:
    handler: handler.text_to_speech
    events:
     - httpApi:
          path: /v1/tts
          method: post

